### ISSUE TITLE
uzem segfault if GAMEFILE is a plain filename

### ISSUE THREAD

**Issue by GoogleCodeExporter** [Uzebox/uzebox#18]
```
What steps will reproduce the problem?

1. Compiled and placed the binaries into ~/bin/ where ~/bin/ is in PATH
2. cd into default/ where my project is located
3. Ran "uzem test1.uze"

What is the expected output? What do you see instead?

uzem should launch but a segmentation fault occurs:

  Using HEX path for SD emulation: test1.uze
  SD Emulation of following files:

  Program received signal SIGSEGV, Segmentation fault.
  0x00007ffff701bda6 in __readdir (dirp=0x0) at ../sysdeps/posix/readdir.c:44
  44	../sysdeps/posix/readdir.c: No such file or directory.
  (gdb) bt
  #0  0x00007ffff701bda6 in __readdir (dirp=0x0) at ../sysdeps/posix/readdir.c:44
  #1  0x0000000000410362 in SDEmu::init_with_directory(char const*) ()
  #2  0x0000000000403847 in avr8::init_sd() ()
  #3  0x0000000000403076 in main ()

What version of the product are you using? On what operating system?

r286 on Linux Ubuntu 14.04

Please provide any additional information below.

uzem runs ok if I run "uzem ./test1.uze" instead:

  Using HEX path for SD emulation: .
  SD Emulation of following files:
  	1: uzeboxSoundEngineCore.o:9460
  [...]

```

Original issue reported on code.google.com by `chris.foo@gmail.com` on 7 Jun 2014 at 6:34

**Comment by uze6666** [comment]
Major reworks in uzem makes this obsolete.
